dict_path = "/home/m2018higarashi/.local/lib/mecab/dic/mecab-ipadic-neologd"
sentiment_path = "/home/m2018higarashi/tools/polarity_dic_News.csv"
# model_path = "/home/m2018higarashi/w2vModel/fr.model"
model_path = "/home/m2018higarashi/w2vModel/entity_vector.model.txt"
sw_path = "/home/m2018higarashi/tools/stopwords.txt"
idf_path = "/home/m2018higarashi/tools/kessan_idfs.pkl"